source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'MyCampus' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyCampus
  pod 'SnapKit', '~> 5.0.0'
  pod 'WMPageController', '~> 2.4.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'MJRefresh'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'RxDataSources', '~> 5.0'
  pod "RTRootNavigationController"
  pod 'IQKeyboardManagerSwift'
  pod 'Toaster'
  pod 'Cache'
  pod 'SwiftDate'
  pod 'YPImagePicker'
  pod 'SwiftMonkeyPaws', '~> 2.1.0'
end

target 'MyCampusUITests' do
  pod 'SwiftMonkey', :git => 'https://github.com/zalando/SwiftMonkey.git'
end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
#    end
#  end
#end
